-- Seed do catálogo de materiais a partir de "Materiais Quadro de comando NICE3000
-- MRL BST VerticalParts.xlsx" (aba COMANDO, 4 variantes 7,5/15kW x 220/380V).
-- Idempotente (ON CONFLICT DO NOTHING) — pode rodar de novo sem duplicar.
-- Divergências já documentadas na aba "Endereçamento" daquela planilha ficam
-- registradas em observacao_divergencia, não resolvidas aqui.

insert into public.materiais_catalogo (sku, descricao, categoria, unidade, fabricante, observacao_divergencia) values
('VPMP-852', 'ADAPTADOR TRILHO DIN TOMADA CSW10A MONT', 'montagem', 'un', null, null),
('VPMP-885', 'ARRUELA DE PRESSÃO M5 ZINCADA', 'fixacao', 'un', null, null),
('VPMP-504', 'BARRAMENTO TERRA 6 POLOS', 'montagem', 'un', null, null),
('VPMP-851', 'BLOCO DE CONTATO AUXILIAR FROTAL BFB-22', 'componente', 'un', null, null),
('VPMP-867', 'BLOCO DE CONTATO AUXILIAR MDWS BC-A MDA', 'componente', 'un', null, null),
('VPMP-550', 'BORNE BTWP 2.5 CINZA', 'componente', 'un', null, null),
('VPMP-853', 'BORNE BTWP 35 CINZA', 'componente', 'un', null, null),
('VPMP-856', 'BOTÃO COM TRAVA COGUMELO VERMELHO (GIRA PARA SOLTAR) 1NF', 'componente', 'un', null, null),
('VPMP-858', 'BOTÃO PULSANTE 1NA VERMELHO', 'componente', 'un', null, null),
('VPMP-859', 'BOTÃO PULSANTE DE SETA 2NA (BRANCO COM SETA PRETA)', 'componente', 'un', null, null),
('VPMP-860', 'BOTÃO PULSANTE DE SETA 2NA (PRETO COM SETA BRANCA)', 'componente', 'un', null, null),
('VPB-383', 'Cabo Flat de 40 Pinos para Conexão entre as Placas MCB e KCB de Elevador', 'componente', 'un', 'BST', null),
('VPMP-057', 'CABO FLEXÍVEL 750V - 0,75MM - PRETO', 'fiacao', 'm', null, null),
('VPMP-883', 'CABO FLEXÍVEL 750V - 0,75MM - VERDE/AMARELO', 'fiacao', 'm', null, null),
('VPMP-841', 'CAIXA PARA QUADRO DE COMANDO - 1 - REF.: VERTICALPARTS', 'caixa', 'un', 'VerticalParts', 'ERP tem VPMP-842 pro mesmo item — possível substituição de SKU, não presumir equivalência sem cadastro técnico confirmado.'),
('VPMP-843', 'CAIXA PARA QUADRO DE COMANDO 2 - REF.: VERTICALPARTS', 'caixa', 'un', 'VerticalParts', null),
('VPMP-882', 'CANALETA PLÁSTICA CINZA COM TAMPA L:30 X A:50', 'montagem', 'm', null, null),
('VPMP-896', 'CHAPA DE SUPORTE PARA PLACA DE INTERFACE MCTC-KCB-B4A Ref.: VerticalParts', 'montagem', 'un', 'VerticalParts', null),
('VPMP-895', 'CHAPA PARA BOTOEIRA DE OPERAÇÃO DE EMERGÊNCIA Ref.: VerticalParts', 'montagem', 'un', 'VerticalParts', null),
('VPMP-794', 'Conector Alojamento Macho Mini Fit, 16 Vias, passo 4,2mm - Ref.: RYNDACK', 'conector', 'un', 'RYNDACK', null),
('VPMP-793', 'CONECTOR ALOJAMENTO MACHO MINIFIT, 14 VIAS, PASSO 4,2MM - REF.: RYNDACK', 'conector', 'un', 'RYNDACK', 'Quantidade zero em todas as variantes da lista original — conferir se este conector é realmente usado nesta família antes de comprar.'),
('VPMP-796', 'CONECTOR ALOJAMENTO MACHO MINIFIT, 2 VIAS, PASSO 4,2MM - REF.: RYNDACK', 'conector', 'un', 'RYNDACK', null),
('VPMP-797', 'CONECTOR ALOJAMENTO MACHO MINIFIT, 4 VIAS, PASSO 4,2MM - REF.: RYNDACK', 'conector', 'un', 'RYNDACK', null),
('VPMP-798', 'CONECTOR ALOJAMENTO MACHO MINIFIT, 6 VIAS, PASSO 4,2MM - REF.: RYNDACK', 'conector', 'un', 'RYNDACK', null),
('VPMP-799', 'CONECTOR ALOJAMENTO MACHO MINIFIT, 8 VIAS, PASSO 4,2MM - REF.: RYNDACK', 'conector', 'un', 'RYNDACK', null),
('VPMP-800', 'CONECTOR ALOJAMENTO MACHO MINIFIT, 10 VIAS, PASSO 4,2MM - REF.: RYNDACK', 'conector', 'un', 'RYNDACK', null),
('VPMP-801', 'CONECTOR ALOJAMENTO MACHO MINIFIT, 12 VIAS, PASSO 4,2MM - REF.: RYNDACK', 'conector', 'un', 'RYNDACK', null),
('VPMP-849', 'CONTATOR AUXILIAR CAWB-32-00D13', 'componente', 'un', null, null),
('VPMP-846', 'CONTATOR DE POTÊNCIA CWB25-11-30D13', 'componente', 'un', null, 'Usado na variante 7,5kW/380V; conferir corrente antes de aplicar em outra variante.'),
('VPMP-847', 'CONTATOR DE POTÊNCIA CWB40-11-30D13', 'componente', 'un', null, 'Usado nas variantes 7,5kW/220V e 15kW/380V; conferir corrente antes de aplicar em outra variante.'),
('VPMP-848', 'CONTATOR DE POTÊNCIA CWB50-11-30D13', 'componente', 'un', null, 'Usado na variante 15kW/220V; conferir corrente antes de aplicar em outra variante.'),
('VPMP-897', 'ESPAÇADOR PLÁSTICO M4 X 10MM SEM ROSCA', 'fixacao', 'un', null, null),
('VPMP-891', 'FECHO LINGUETA COM DOBRA 2X45MM TRIÂNGULO PRETO', 'fixacao', 'un', null, null),
('VPMP-761', 'INTERRUPTOR DIFERENCIAL RESIDUAL RDWS-AC-30-25-2', 'componente', 'un', null, 'Aba Endereçamento aponta divergência com o esquema: lista traz 3 DR de 25A, desenho mostra 2 de 6A/30mA — confirmar com engenharia antes de fabricar.'),
('VPMP-850', 'MINICONTATOR CWC012-01-30D13', 'componente', 'un', null, null),
('VPMP-333', 'MINIDISJUNTOR MONOPOLAR MDWP-C6 CURVA C', 'componente', 'un', null, 'Aba Endereçamento aponta divergência com o esquema: lista traz 3×1P C6, desenho mostra 1P/1A e 2P/6A — confirmar com engenharia antes de fabricar.'),
('VPMP-865', 'MINIDISJUNTOR TRIPOLAR MDWS-C50-3-10kA (IEC 60947-2)', 'componente', 'un', null, 'Aba Endereçamento aponta divergência de polos com o esquema (lista 3P, desenho 4P) — confirmar antes de fabricar.'),
('VPMP-864', 'MINIDISJUNTOR TRIPOLAR MDWS-C70-3-10kA (IEC 60947-2)', 'componente', 'un', null, 'Aba Endereçamento aponta divergência de polos com o esquema (lista 3P, desenho 4P) — confirmar antes de fabricar.'),
('VPMP-305', 'PARAFUSO PHILLIPS (DIN7985) - MA5 X 8PAN', 'fixacao', 'un', null, null),
('VPMP-159', 'PARAFUSO PHILLIPS MÁQUINA PANELA MA - 4 X 16', 'fixacao', 'un', null, null),
('VPB-157', 'Placa de Freio com Ajuste de Tensão 48~207Vcc do Quadro de Comando de Elevador', 'placa', 'un', 'BST', 'Aba Endereçamento aponta "tensão de saída divergente" em relação ao esquema — confirmar com engenharia.'),
('VPB-156', 'Placa de Interface B4A para Conexão do Quadro de Comando MRL de Elevador', 'placa', 'un', 'BST', null),
('VPMP-855', 'POSTE FINAL PF3-BTW CINZA', 'componente', 'un', null, null),
('VPMP-178', 'REBITE POP (T-412) - 12,0MM x 4,0MM', 'fixacao', 'un', null, null),
('VPMP-890', 'SUPORTE INCLINADO 45º PARA TRILHO DIN', 'montagem', 'un', null, null),
('VPMP-854', 'TAMPA DE FECHAMENTO DE BORNE TF-BTWP-2.5-10 CINZA', 'componente', 'un', null, null),
('VPMP-795', 'TERMINAL PARA ALOJAMENTO MACHO MINI FIT, PASSO 4,20MM - REF.: RYNDACK', 'terminal', 'un', 'RYNDACK', null),
('VPMP-889', 'TERMINAL PRÉ ISOLADO FORQUILHA - 1,5MM - M5', 'terminal', 'un', null, null),
('VPMP-390', 'TERMINAL TUBULAR DUPLO - 0,75MM', 'terminal', 'un', null, null),
('VPMP-084', 'TERMINAL TUBULAR SIMPLES - 0,75MM', 'terminal', 'un', null, null),
('VPMP-898', 'TRANSFORMADOR ISOLADOR ENTRADA:220VCA / SAÍDA:110VCA (1.36A) 150VA CLASSE: F, 50/60HZ', 'componente', 'un', null, 'Aba Endereçamento aponta divergência com o esquema: lista 220/110V 150VA, desenho mostra 220/125V 63/110VA — confirmar antes de fabricar.'),
('VPMP-112', 'TRILHO DIN 35MM PERFURADO', 'montagem', 'm', null, null),
('VPMP-861', 'BLOCO DE CONTATO NA - BC10F-CSW', 'componente', 'un', null, null),
('VPMP-862', 'BLOCO DE CONTATO NF - BC01F-CSW', 'componente', 'un', null, null),
('VPMP-054', 'CABO FLEXÍVEL 750V - 0,75MM - AZUL', 'fiacao', 'm', null, null),
('VPMP-263', 'CABO FLEXÍVEL 750V - 6,0MM - PRETO', 'fiacao', 'm', null, 'Mesmo código usado como 6mm² em 3 variantes e como 10mm² na variante 15kW/220V — confirmar bitola real antes de cortar/comprar.'),
('VPMP-884', 'CABO FLEXÍVEL 750V - 6,0MM - VERDE/AMARELO', 'fiacao', 'm', null, null),
('VPMP-886', 'CABO FLEXÍVEL 750V - 10,0MM - VERDE/AMARELO', 'fiacao', 'm', null, null),
('VPMP-857', 'COMUTADOR DE 2 POSIÇÃO FIXO 45° KNOB CURTO PRETO', 'componente', 'un', null, 'Mesmo SKU aplicado a 3 composições de contato diferentes (2NA / 2NA+2NF / 2NF) na planilha original — conferir qual composição antes de montar.'),
('VPMP-863', 'FLANGE - AF3F', 'montagem', 'un', null, null),
('VPB-225', 'Inversor de Frequência Trifásico, 15kW/380V - Ref.: BST (NICE-L-C-4015-KZG)', 'placa', 'un', 'BST', null),
('VPB-223', 'Inversor de Frequência Trifásico, 7,5kW/380V - Ref.: BST (NICE-L-C-4007-KZG)', 'placa', 'un', 'BST', null),
('VPB-224', 'Inversor de Frequência Trifásico, 15kW/220V - Ref.: BST (NICE-L-C-2015-KZG)', 'placa', 'un', 'BST', null),
('VPB-196', 'Inversor de Frequência Trifásico - Ref.: BST', 'placa', 'un', 'BST', 'CRÍTICO: na planilha original este código aparece rotulado "7,5kW/220V" mas com descrição/código de "15kW/380V" (NICE-L-C-4015-KZG) — não liberar para compra/fabricação sem corrigir com o fabricante.'),
('VPB-381', 'Resgate Manual no Comando para Elevador Sem Casa de Máquinas', 'placa', 'un', 'BST', null),
('VPMP-902', 'RESISTOR DE FRENAGEM - 40 OHM - 4500W', 'componente', 'un', null, null),
('VPMP-901', 'RESISTOR DE FRENAGEM - 75 OHM - 2500W', 'componente', 'un', null, null),
('VPMP-900', 'RESISTOR DE FRENAGEM - 13 OHM - 4500W', 'componente', 'un', null, null),
('VPMP-899', 'RESISTOR DE FRENAGEM - 25 OHM - 4500W', 'componente', 'un', null, null),
('VPMP-212', 'TERMINAL PRÉ ISOLADO OLHAL 6,00MM', 'terminal', 'un', null, null),
('VPMP-888', 'TERMINAL PRÉ ISOLADO FORQUILHA - 6MM - M6', 'terminal', 'un', null, 'Mesmo SKU registrado como terminal de 6mm² em 3 variantes e de 10mm² na variante 15kW/220V — confirmar antes de cortar/comprar.'),
('VPMP-393', 'TERMINAL TUBULAR SIMPLES - 6,0MM', 'terminal', 'un', null, null),
('VPMP-385', 'TERMINAL TUBULAR SIMPLES - 2,5MM', 'terminal', 'un', null, null),
('VPMP-392', 'TERMINAL TUBULAR DUPLO - 6,0MM', 'terminal', 'un', null, null),
('VPMP-663', 'TERMINAL TUBULAR SIMPLES - 10,0MM', 'terminal', 'un', null, null),
('VPMP-265', 'CABO FLEXÍVEL 750V - 2,5MM - PRETO', 'fiacao', 'm', null, null),
('VPMP-242', 'ABRACADEIRA DE NYLON - 160 X 2,5MM (NATURAL)', 'fixacao', 'un', null, null)
on conflict (sku) do nothing;
