alter table public.pcp_produtos add column if not exists endereco text;
update pcp_produtos set endereco='I 02' where codigo='VPB-112';
update pcp_produtos set endereco='I 01   R1 - 01' where codigo='VPB-225';
update pcp_produtos set endereco='J 13' where codigo='VPMP-084';
update pcp_produtos set endereco='J 14' where codigo='VPMP-212';
update pcp_produtos set endereco='J 02' where codigo='VPMP-333';
update pcp_produtos set endereco='J 13' where codigo='VPMP-390';
update pcp_produtos set endereco='J 13' where codigo='VPMP-392';
update pcp_produtos set endereco='J 13' where codigo='VPMP-393';
update pcp_produtos set endereco='J 14' where codigo='VPMP-470';
update pcp_produtos set endereco='J 07' where codigo='VPMP-588';
update pcp_produtos set endereco='J 13' where codigo='VPMP-629';
update pcp_produtos set endereco='J 14' where codigo='VPMP-630';
update pcp_produtos set endereco='J 13' where codigo='VPMP-663';
update pcp_produtos set endereco='J 06' where codigo='VPMP-793';
update pcp_produtos set endereco='J06' where codigo='VPMP-794';
update pcp_produtos set endereco='J 06' where codigo='VPMP-795';
update pcp_produtos set endereco='J 06' where codigo='VPMP-796';
update pcp_produtos set endereco='J 06' where codigo='VPMP-797';
update pcp_produtos set endereco='J 06' where codigo='VPMP-798';
update pcp_produtos set endereco='J 06' where codigo='VPMP-800';
update pcp_produtos set endereco='J06' where codigo='VPMP-801';
update pcp_produtos set endereco='J 08' where codigo='VPMP-851';
update pcp_produtos set endereco='J 13' where codigo='VPMP-887';
update pcp_produtos set endereco='J 13' where codigo='VPMP-888';
update pcp_produtos set endereco='J 13' where codigo='VPMP-889';